/**
 * The shared runtime, and the properties that make it shippable (MAR-887, ADR 0034).
 *
 * `tests/agent-kit.test.ts`, `tests/legacy-agent.test.ts`,
 * `tests/scout-curates.test.ts` and `tools/dash-mcp/tests/template-run.test.ts`
 * all prove behaviour by spawning a program. This file proves the three things
 * none of them can, because each is a property of the *file* rather than of a
 * run:
 *
 * 1. **It needs no registry.** A scaffolded project declares no dependencies
 *    and the packaged sample is copied as raw bytes, so a single bare import
 *    specifier in this file would turn "create it, run it, add it" into a
 *    journey that needs npm and a network. Nothing at run time would catch it
 *    in this repository, where `node_modules` is always there.
 * 2. **Both scaffolders write it, and write the same bytes.** One runtime is
 *    the whole point; two copies that drift are worse than the fork this packet
 *    removed, because the second copy looks maintained.
 * 3. **The templates carry no mechanics any more.** A template that kept its
 *    own `emit` beside the SDK's would emit twice, and the symptom would be a
 *    duplicated event rather than an error.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { planScaffold, type TemplateSources } from "../agent-kit/scaffold";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SDK_PATH = path.join(repoRoot, "agent-kit", "template", "dash-agent-sdk.mjs");
const SDK_SOURCE = readFileSync(SDK_PATH, "utf8");
const KIT_TEMPLATE = readFileSync(
  path.join(repoRoot, "agent-kit", "template", "agent.mjs"),
  "utf8",
);
const MCP_TEMPLATE = readFileSync(
  path.join(repoRoot, "tools", "dash-mcp", "template", "agent.mjs"),
  "utf8",
);

const sdk = (await import("../agent-kit/template/dash-agent-sdk.mjs")) as {
  SDK_VERSION: string;
  PROTOCOL_VERSION: number;
  startAgent: unknown;
  readManifest: unknown;
  ask: unknown;
  browse: unknown;
  log: unknown;
  canonicaliseItems: (items: readonly { headline?: string }[]) => string;
  fingerprintItems: (items: readonly { headline?: string }[]) => string;
};

describe("the runtime file", () => {
  it("imports nothing but node builtins, so a scaffold needs no registry", () => {
    /*
     * The property the whole file shape exists for. `agent-kit/scaffold.ts`
     * writes `dependencies: {}` on purpose and `scripts/build-shell.mjs` copies
     * these bytes into the package with no install step anywhere near them, so
     * one bare specifier here is an agent that cannot start on a machine that
     * has never run `npm install` — which is every machine the installed
     * journey runs on.
     */
    const specifiers = [...SDK_SOURCE.matchAll(/(?:^|\n)import[^\n]*?from\s+"([^"]+)"/g)].map(
      (match) => match[1],
    );
    expect(specifiers.length).toBeGreaterThan(0);
    for (const specifier of specifiers) {
      expect(specifier.startsWith("node:")).toBe(true);
    }
    // And no dynamic escape hatch, which the regex above would not see.
    expect(SDK_SOURCE).not.toMatch(/\brequire\s*\(/);
    expect(SDK_SOURCE).not.toMatch(/\bimport\s*\(/);
  });

  it("carries a version and says it is not the file to edit", () => {
    // The version is what makes an upgrade expressible at all: see
    // `docs/foundation/sdk-upgrades.md`. A future check compares this string
    // and replaces this file only, never `agent.mjs`.
    expect(sdk.SDK_VERSION).toMatch(/^\d+\.\d+\.\d+$/);
    expect(sdk.PROTOCOL_VERSION).toBe(1);
    expect(SDK_SOURCE).toContain("Do not edit this file");
  });

  it("exports the surface the templates and DASH's own mirror test use", () => {
    for (const name of [
      "startAgent",
      "readManifest",
      "ask",
      "browse",
      "log",
      "canonicaliseItems",
      "fingerprintItems",
    ] as const) {
      expect(typeof sdk[name]).toBe("function");
    }
  });

  it("keeps the fingerprint DASH recomputes, which moved here from its own file", () => {
    // Held byte for byte against `lib/brief/fingerprint.ts` by
    // `tools/dash-mcp/tests/fingerprint-mirror.test.ts`. This is only the
    // shape: a hex digest, and order as part of the identity.
    expect(sdk.fingerprintItems([{ headline: "a" }])).toMatch(/^[0-9a-f]{64}$/);
    expect(sdk.fingerprintItems([{ headline: "a" }, { headline: "b" }])).not.toBe(
      sdk.fingerprintItems([{ headline: "b" }, { headline: "a" }]),
    );
  });
});

describe("the templates that import it", () => {
  it("both import the runtime from beside themselves", () => {
    for (const template of [KIT_TEMPLATE, MCP_TEMPLATE]) {
      expect(template).toContain('from "./dash-agent-sdk.mjs"');
    }
  });

  it("neither keeps a second copy of the mechanics", () => {
    /*
     * The failure this catches is additive rather than absent: a template that
     * kept its own `emit` or its own stdin loop beside the SDK's would send
     * every event twice and acknowledge every command twice, and DASH would
     * show a plausible-looking run built out of duplicates.
     */
    for (const template of [KIT_TEMPLATE, MCP_TEMPLATE]) {
      expect(template).not.toContain("process.stdin.on");
      expect(template).not.toContain('type: "telemetry"');
      expect(template).not.toContain('type: "artifact"');
      expect(template).not.toContain('process.on("SIGTERM"');
    }
  });

  it("tells whoever edits them which file is theirs", () => {
    for (const template of [KIT_TEMPLATE, MCP_TEMPLATE]) {
      expect(template).toContain("dash-agent-sdk.mjs");
      expect(template).toContain("upgrades that file in place");
    }
  });
});

describe("what a scaffold writes", () => {
  it("places the runtime beside the program, verbatim", () => {
    const sources: TemplateSources = {
      agent: "// the agent\n",
      sdk: SDK_SOURCE,
      openInDash: "// bundled by scripts/build-agent-kit.mjs\n",
    };
    const planned = planScaffold(
      {
        directory: path.join(repoRoot, "not-written-anywhere"),
        agent_id: "folder-digest",
        display_name: "Folder digest",
        summary: "Reads what you choose and writes a short summary.",
        kit_version: "0.1.1",
        now: new Date("2026-09-07T12:00:00.000Z"),
      },
      sources,
    );

    expect(planned.ok).toBe(true);
    if (!planned.ok) {
      return;
    }
    const byPath = new Map(planned.files.map((file) => [file.path, file.contents]));
    expect(byPath.get("dash-agent-sdk.mjs")).toBe(SDK_SOURCE);
    // Beside the program rather than under a folder: `agent.mjs` imports it as
    // `./dash-agent-sdk.mjs`, and DASH's import splits the project into
    // `<agent>/code/` as a unit, so the two must travel together.
    expect(byPath.has("agent.mjs")).toBe(true);
  });

  it("declares no dependencies, which is what makes the runtime a file", () => {
    const planned = planScaffold(
      {
        directory: path.join(repoRoot, "not-written-anywhere"),
        agent_id: "folder-digest",
        display_name: "Folder digest",
        summary: "Reads what you choose and writes a short summary.",
        kit_version: "0.1.1",
        now: new Date("2026-09-07T12:00:00.000Z"),
      },
      { agent: "// a\n", sdk: "// b\n", openInDash: "// c\n" },
    );
    expect(planned.ok).toBe(true);
    if (!planned.ok) {
      return;
    }
    const projectPackage = JSON.parse(
      planned.files.find((file) => file.path === "package.json")?.contents ?? "{}",
    ) as { dependencies: Record<string, string> };
    expect(projectPackage.dependencies).toEqual({});
  });
});
