/**
 * A real error and a real retry, on the right step (MAR-889).
 *
 * This is stage 3's acceptance criterion, and it is written the way the criterion
 * is worded: **a real error and a real retry**. Nothing here is a fixture list of
 * spans handed to a builder. An ordinary program using the shipped runtime is
 * spawned by a real `Supervisor` over a real pipe; its source fetch throws the
 * first time it is called; the spans come off `drainSpans` in the bytes the
 * child actually wrote; every one of them is put through the contract; and the
 * tree is built by the same function the run page uses.
 *
 * The failure this catches is the one a fixture test cannot: the SDK sending
 * nothing, sending the wrong parent, or closing a step span against the wrong
 * operation. `tests/run-trace-view.test.ts` covers the shapes that are hard to
 * produce on purpose — an orphan, a cycle, a run that died mid-span — and this
 * file covers the one that has to be true of the real thing.
 *
 * `tests/legacy-agent.test.ts` is the compatibility half and is unaffected: an
 * agent that predates the SDK writes no `trace` lines, so its drain is empty and
 * DASH says the run has no step trace.
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it } from "vitest";

import { scaffoldManifest } from "../agent-kit/scaffold";
import { validateSpan, type RunSpan } from "../lib/contracts";
import { buildRunTrace, type TraceNode } from "../lib/views/run-trace";
import { Supervisor } from "../runner/supervisor";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SDK = path.join(repoRoot, "agent-kit", "template", "dash-agent-sdk.mjs");
const PROGRAM = path.join(repoRoot, "tests", "fixtures", "retrying-agent.mjs");
const AGENT_ID = "retrying-scout";

const roots: string[] = [];
const supervisors: Supervisor[] = [];

afterAll(async () => {
  for (const supervisor of supervisors) {
    supervisor.stopAll();
  }
  /*
   * Waited on rather than fired and forgotten. A `rmSync` racing a child that
   * still has the directory open is the EPERM this repository has paid for
   * before; the wait is the fix and the try/catch below is only the belt.
   */
  await waitFor(
    () =>
      supervisors.every((supervisor) =>
        supervisor.list().every((agentId) => supervisor.facts(agentId)?.pid === null),
      ),
    "the fixture agent's process to stop",
  );
  for (const root of roots) {
    try {
      rmSync(root, { recursive: true, force: true });
    } catch {
      // Windows refuses to remove a directory a process still holds open, and a
      // temp directory that would not delete is not a failed test.
    }
  }
});

/**
 * The fixture agent's folder on disk: the program, the runtime beside it, and a
 * manifest generated by the kit.
 *
 * The runtime is copied rather than imported from the checkout, because that is
 * what a real agent folder holds — ADR 0034 makes the folder the unit and the
 * import a relative one. A test that let the program reach up into the
 * repository would be testing a layout no user has.
 */
function project(): string {
  const root = mkdtempSync(path.join(tmpdir(), "dash-trace-"));
  roots.push(root);
  const directory = path.join(root, AGENT_ID);
  mkdirSync(directory, { recursive: true });

  writeFileSync(path.join(directory, "agent.mjs"), readFileSync(PROGRAM, "utf8"), "utf8");
  writeFileSync(path.join(directory, "dash-agent-sdk.mjs"), readFileSync(SDK, "utf8"), "utf8");
  writeFileSync(
    path.join(directory, "agent.manifest.json"),
    `${JSON.stringify(
      scaffoldManifest({
        directory,
        agent_id: AGENT_ID,
        display_name: "Retrying scout",
        summary: "An agent whose source fetch fails once and then succeeds.",
        kit_version: "0.1.1",
        now: new Date("2026-09-07T12:00:00.000Z"),
      }),
      null,
      2,
    )}\n`,
    "utf8",
  );
  return directory;
}

function startedSupervisor(directory: string): Supervisor {
  const supervisor = new Supervisor(
    [
      {
        agent_id: AGENT_ID,
        manifest_path: path.join(directory, "agent.manifest.json"),
        command: process.execPath,
        args: [path.join(directory, "agent.mjs")],
        cwd: directory,
      },
    ],
    () => {},
  );
  supervisors.push(supervisor);
  supervisor.start(AGENT_ID);
  return supervisor;
}

async function waitFor(predicate: () => boolean, label: string, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (predicate()) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error(`Timed out waiting for: ${label}`);
}

/**
 * Run the fixture once and collect every span it wrote.
 *
 * Drained repeatedly, because `drainSpans` empties the buffer and DASH's own
 * poll is a five-second loop — a single drain at the end would be a test that
 * passes only because the run was short.
 */
async function tracedRun(): Promise<{ spans: RunSpan[]; dropped: number }> {
  const supervisor = startedSupervisor(project());
  await waitFor(() => supervisor.report(AGENT_ID) !== null, "startup");

  const collected: RunSpan[] = [];
  let dropped = 0;
  const take = (): void => {
    const drain = supervisor.drainSpans();
    dropped += drain.dropped;
    for (const buffered of drain.spans) {
      const result = validateSpan(buffered.span);
      // Every candidate through the contract, not just the ones that look
      // right. A span the schema would refuse is a defect in the SDK, and
      // collecting it silently would hide it behind a passing tree.
      expect(result, JSON.stringify(buffered.span)).toMatchObject({ ok: true });
      if (result.ok) {
        // The provenance the runner attaches, checked here because DASH's ingest
        // checks it and a fixture that disagreed would prove nothing.
        expect(buffered.agent_id).toBe(AGENT_ID);
        collected.push(result.value);
      }
    }
  };

  await supervisor.deliver(AGENT_ID, {
    command_id: `cmd-trace-${String(Date.now())}`,
    command: "retry",
    target: { agent_id: AGENT_ID, task_id: "waiting-to-be-run" },
  });

  await waitFor(
    () => {
      take();
      return collected.some((span) => span.kind === "run" && span.ended_at !== null);
    },
    "the run's own span to close",
  );
  take();

  return { spans: collected, dropped };
}

/** The last write for each span id — what DASH's upsert leaves in the row. */
function settled(spans: readonly RunSpan[]): RunSpan[] {
  const byId = new Map<string, RunSpan>();
  for (const span of spans) {
    byId.set(span.span_id, span);
  }
  return [...byId.values()];
}

function flatten(nodes: readonly TraceNode[]): TraceNode[] {
  return nodes.flatMap((node) => [node, ...flatten(node.children)]);
}

describe("a run that failed once and then worked", () => {
  it("puts the error and the retry on the step they happened in", async () => {
    const { spans, dropped } = await tracedRun();
    expect(dropped).toBe(0);

    const rows = settled(spans);
    const trace = buildRunTrace(rows, { dropped, runIsOver: true });

    // Nothing was orphaned and nothing was lost: every span the agent wrote is
    // reachable from the run's own root. This is the assertion that fails if
    // parentage is taken from a global rather than from the calling context.
    expect(trace.orphans).toEqual([]);
    expect(trace.roots).toHaveLength(1);
    expect(trace.total).toBe(rows.length);

    const root = trace.roots[0] as TraceNode;
    expect(root.span.kind).toBe("run");
    expect(root.span.status).toBe("ok");

    // Two steps, in the order the program calls them, both under the run.
    const steps = root.children.filter((node) => node.span.kind === "step");
    expect(steps.map((node) => node.span.name)).toEqual([
      "Read the sources",
      "Write what it found",
    ]);

    /*
     * The heart of the acceptance criterion. Both attempts are children of the
     * *first* step — not of the run, not of the second step — and they are two
     * spans rather than one amended one, so the try that failed is still on the
     * page beside the try that worked.
     */
    const fetches = (steps[0] as TraceNode).children.filter(
      (node) => node.span.kind === "source_fetch",
    );
    expect(fetches).toHaveLength(2);
    expect(fetches.map((node) => node.span.status)).toEqual(["error", "ok"]);
    expect(fetches[0]?.span.attributes?.["attempt"]).toBe(1);
    expect(fetches[1]?.span.attributes?.["attempt"]).toBe(2);

    // The real message, from the real throw, on the operation it belongs to.
    expect(fetches[0]?.span.error?.message).toBe("the newsroom feed did not answer");
    expect(fetches[1]?.span.error ?? null).toBeNull();

    // And the failure did not leak upwards. A step that recovered is finished
    // and the run completed: a trace that reported the step as failed because
    // something inside it did would send a person to the wrong place.
    expect((steps[0] as TraceNode).span.status).toBe("ok");

    // The digest span is under the second step, where the program emitted it.
    const artifacts = flatten(trace.roots).filter((node) => node.span.kind === "artifact");
    expect(artifacts).toHaveLength(1);
    expect(artifacts[0]?.span.attributes?.["item_count"]).toBe(1);
  }, 40_000);

  it("closes every span it opened, so nothing reads as unfinished", async () => {
    const { spans } = await tracedRun();

    /*
     * Each span is written twice — open, then close — and this is where that
     * contract is checked against the real stream rather than asserted about
     * the code. An open write carries `ended_at: null` and `status: "unknown"`;
     * a close carries both. A run that emitted only closes would draw nothing
     * while it was running, and a run that emitted only opens would read as
     * having died in every operation at once.
     */
    const opens = spans.filter((span) => span.ended_at === null);
    const closes = spans.filter((span) => span.ended_at !== null);
    expect(opens.length).toBeGreaterThan(0);
    expect(opens.every((span) => span.status === "unknown")).toBe(true);
    expect(new Set(closes.map((span) => span.span_id))).toEqual(
      new Set(opens.map((span) => span.span_id)),
    );
    expect(closes.every((span) => span.status !== "unknown")).toBe(true);
  }, 40_000);

  it("names the run it belongs to, and only that run", async () => {
    const { spans } = await tracedRun();

    // One run id across every span, matching the telemetry the same run wrote.
    // This is the join the whole feature rests on: a span whose `run_id` did not
    // match would be a tree drawn on a page about a different run.
    const runIds = new Set(spans.map((span) => span.run_id));
    expect(runIds.size).toBe(1);
    expect(spans.every((span) => span.agent === AGENT_ID)).toBe(true);
    expect(spans.every((span) => span.trace_version === 1)).toBe(true);
  }, 40_000);
});
